# Generated by Django 4.1.1 on 2022-09-23 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('gu_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gu_id', models.CharField(max_length=20, null=True, verbose_name='아이디')),
                ('gu_pw', models.CharField(max_length=16, null=True, verbose_name='비밀번호')),
                ('gu_name', models.CharField(max_length=6, null=True, verbose_name='이름')),
                ('gu_gender', models.CharField(default='M', max_length=1, null=True, verbose_name='성별')),
                ('gu_birth_date', models.CharField(max_length=20, null=True, verbose_name='생년월일')),
                ('gu_email', models.CharField(max_length=40, null=True, verbose_name='이메일')),
                ('gu_phone_number', models.CharField(max_length=11, null=True, verbose_name='핸드폰번호')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('gr_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gr_nickname', models.CharField(max_length=10, null=True, verbose_name='닉네임')),
                ('gr_place', models.CharField(max_length=20, null=True, verbose_name='장소')),
                ('gr_comment', models.CharField(max_length=100, null=True, verbose_name='코멘트')),
                ('gr_grade', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='평점')),
                ('gr_gu_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gr_gu_seq', to='groad.user', verbose_name='리뷰어')),
            ],
        ),
        migrations.CreateModel(
            name='qrcode',
            fields=[
                ('gq_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gq_qrcode', models.CharField(max_length=100, null=True, verbose_name='qrcode')),
                ('gq_gu_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gq_gu_seq', to='groad.user', verbose_name='순례자')),
            ],
        ),
        migrations.CreateModel(
            name='pedometer',
            fields=[
                ('gp_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gp_step', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='걸음수')),
                ('gp_gu_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_gu_seq', to='groad.user', verbose_name='순례자')),
            ],
        ),
        migrations.CreateModel(
            name='alarm',
            fields=[
                ('ga_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('ga_onoff1', models.BooleanField(default=False)),
                ('ga_onoff2', models.BooleanField(default=False)),
                ('ga_onoff3', models.BooleanField(default=False)),
                ('ga_gu_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_gu_seq', to='groad.user', verbose_name='알리머')),
            ],
        ),
    ]
