# Generated by Django 4.0.6 on 2022-11-01 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursePosition',
            fields=[
                ('gc_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gc_main_image', models.CharField(max_length=100, null=True)),
                ('gc_sub_image1', models.CharField(max_length=100, null=True)),
                ('gc_sub_image2', models.CharField(max_length=100, null=True)),
                ('gc_sub_image3', models.CharField(max_length=100, null=True)),
                ('gc_text', models.CharField(max_length=2000, null=True)),
                ('gc_traffic12', models.CharField(max_length=1000, null=True)),
                ('gc_traffic23', models.CharField(max_length=1000, null=True)),
                ('gc_traffic34', models.CharField(max_length=1000, null=True)),
                ('gc_traffic45', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
