# Generated by Django 4.0.6 on 2022-11-01 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0002_courseposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='course2Position',
            fields=[
                ('gc_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gc_main_image', models.CharField(max_length=100, null=True)),
                ('gc_sub_image1', models.CharField(max_length=100, null=True)),
                ('gc_sub_image2', models.CharField(max_length=100, null=True)),
                ('gc_sub_image3', models.CharField(max_length=100, null=True)),
                ('gc_text', models.CharField(max_length=2000, null=True)),
                ('gc_traffic12', models.CharField(max_length=1000, null=True)),
                ('gc_traffic23', models.CharField(max_length=1000, null=True)),
                ('gc_traffic34', models.CharField(max_length=1000, null=True)),
                ('gc_traffic45', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course3Position',
            fields=[
                ('gc_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gc_main_image', models.CharField(max_length=100, null=True)),
                ('gc_sub_image1', models.CharField(max_length=100, null=True)),
                ('gc_sub_image2', models.CharField(max_length=100, null=True)),
                ('gc_sub_image3', models.CharField(max_length=100, null=True)),
                ('gc_text', models.CharField(max_length=2000, null=True)),
                ('gc_traffic12', models.CharField(max_length=1000, null=True)),
                ('gc_traffic23', models.CharField(max_length=1000, null=True)),
                ('gc_traffic34', models.CharField(max_length=1000, null=True)),
                ('gc_traffic45', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course4Position',
            fields=[
                ('gc_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gc_main_image', models.CharField(max_length=100, null=True)),
                ('gc_sub_image1', models.CharField(max_length=100, null=True)),
                ('gc_sub_image2', models.CharField(max_length=100, null=True)),
                ('gc_sub_image3', models.CharField(max_length=100, null=True)),
                ('gc_text', models.CharField(max_length=2000, null=True)),
                ('gc_traffic12', models.CharField(max_length=1000, null=True)),
                ('gc_traffic23', models.CharField(max_length=1000, null=True)),
                ('gc_traffic34', models.CharField(max_length=1000, null=True)),
                ('gc_traffic45', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='coursePosition',
            new_name='course1Position',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='gq_gu_seq',
        ),
        migrations.DeleteModel(
            name='pedometer',
        ),
        migrations.DeleteModel(
            name='qrcode',
        ),
    ]
