# Generated by Django 4.0.6 on 2022-11-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0003_course2position_course3position_course4position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gr_content_image',
            field=models.CharField(max_length=500, null=True, verbose_name='장소'),
        ),
    ]
