# Generated by Django 4.0.6 on 2022-11-03 09:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0004_review_gr_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course1position',
            name='gc_main_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course1position',
            name='gc_sub_image1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course1position',
            name='gc_sub_image2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course1position',
            name='gc_sub_image3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course2position',
            name='gc_main_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course2position',
            name='gc_sub_image1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course2position',
            name='gc_sub_image2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course2position',
            name='gc_sub_image3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course3position',
            name='gc_main_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course3position',
            name='gc_sub_image1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course3position',
            name='gc_sub_image2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course3position',
            name='gc_sub_image3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course4position',
            name='gc_main_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course4position',
            name='gc_sub_image1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course4position',
            name='gc_sub_image2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course4position',
            name='gc_sub_image3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('gi_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gi_title', models.CharField(max_length=30, null=True)),
                ('gi_contents', models.CharField(max_length=30, null=True)),
                ('gi_gu_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gi_gu_seq', to='groad.user')),
            ],
        ),
    ]
