# Generated by Django 4.0.6 on 2022-11-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0005_alter_course1position_gc_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='gi_contents',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
