# Generated by Django 4.0.6 on 2022-11-04 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0007_setting_delete_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gu_point_number',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='포인트'),
        ),
    ]
