# Generated by Django 4.0.6 on 2022-11-06 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0008_user_gu_point_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelcourse1',
            fields=[
                ('gt_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
            ],
        ),
        migrations.CreateModel(
            name='travelcourse2',
            fields=[
                ('gt_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
            ],
        ),
        migrations.CreateModel(
            name='travelcourse3',
            fields=[
                ('gt1_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
            ],
        ),
        migrations.CreateModel(
            name='travelcourse4',
            fields=[
                ('gt1_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
            ],
        ),
    ]
