# Generated by Django 4.0.6 on 2022-11-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0009_travelcourse1_travelcourse2_travelcourse3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelcourse3',
            old_name='gt1_seq',
            new_name='gt_seq',
        ),
        migrations.RenameField(
            model_name='travelcourse4',
            old_name='gt1_seq',
            new_name='gt_seq',
        ),
    ]
