# Generated by Django 4.0.6 on 2022-11-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0011_travelcourse1_gt_camera_lat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='travelcourse1',
            new_name='travelcourse',
        ),
        migrations.DeleteModel(
            name='travelcourse2',
        ),
        migrations.DeleteModel(
            name='travelcourse3',
        ),
        migrations.DeleteModel(
            name='travelcourse4',
        ),
    ]
