# Generated by Django 4.0.6 on 2022-11-09 11:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0013_course5position_course6position_course7position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gu_profile_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='review_share',
            fields=[
                ('grs_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('grc_flag', models.BooleanField(default=False)),
                ('grc_gr_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grs_gr_seq', to='groad.review')),
                ('grc_gu_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grs_gu_seq', to='groad.user')),
            ],
        ),
        migrations.CreateModel(
            name='review_comment',
            fields=[
                ('grc_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('grc_name', models.CharField(max_length=20, null=True)),
                ('grc_profile_image', models.CharField(max_length=500, null=True)),
                ('grc_comment', models.CharField(max_length=300, null=True)),
                ('grc_gr_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grc_gr_seq', to='groad.review')),
            ],
        ),
    ]
