# Generated by Django 4.0.6 on 2022-11-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0014_user_gu_profile_image_review_share_review_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_share',
            old_name='grc_flag',
            new_name='grs_flag',
        ),
        migrations.RenameField(
            model_name='review_share',
            old_name='grc_gr_seq',
            new_name='grs_gr_seq',
        ),
        migrations.RenameField(
            model_name='review_share',
            old_name='grc_gu_seq',
            new_name='grs_gu_seq',
        ),
    ]
