# Generated by Django 4.0.6 on 2022-11-09 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0016_remove_review_gr_auth_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_comment',
            name='grc_comment_count',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='review_share',
            name='grc_auth_count',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
