# Generated by Django 4.0.6 on 2022-11-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0017_alter_review_comment_grc_comment_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_share',
            old_name='grc_auth_count',
            new_name='grs_auth_count',
        ),
    ]
