# Generated by Django 4.0.6 on 2022-11-11 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0020_review_gr_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='gr_profile_image',
        ),
    ]
