# Generated by Django 4.0.6 on 2022-11-12 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0022_review_gr_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cafe_list',
            fields=[
                ('gcl_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gcl_main_image', models.CharField(max_length=500, null=True)),
                ('gcl_name', models.CharField(max_length=100, null=True)),
                ('gcl_lat', models.FloatField(null=True)),
                ('gcl_lng', models.FloatField(null=True)),
                ('gcl_info', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lodging_list',
            fields=[
                ('gll_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gll_main_image', models.CharField(max_length=500, null=True)),
                ('gll_name', models.CharField(max_length=100, null=True)),
                ('gll_lat', models.FloatField(null=True)),
                ('gll_lng', models.FloatField(null=True)),
                ('gll_info', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='photo_list',
            fields=[
                ('gpl_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('gpl_main_image', models.CharField(max_length=500, null=True)),
                ('gpl_name', models.CharField(max_length=100, null=True)),
                ('gpl_lat', models.FloatField(null=True)),
                ('gpl_lng', models.FloatField(null=True)),
                ('gpl_info', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant_list',
            fields=[
                ('grl_seq', models.AutoField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='시퀀스')),
                ('grl_main_image', models.CharField(max_length=500, null=True)),
                ('grl_name', models.CharField(max_length=100, null=True)),
                ('grl_lat', models.FloatField(null=True)),
                ('grl_lng', models.FloatField(null=True)),
                ('grl_info', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
