# Generated by Django 4.0.6 on 2022-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groad', '0023_cafe_list_lodging_list_photo_list_restaurant_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe_list',
            name='gcl_course',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lodging_list',
            name='gll_course',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='photo_list',
            name='gpl_course',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_list',
            name='grl_course',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
